/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRequestsRouteImport } from './routes/staff-requests'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompounderRouteImport } from './routes/compounder'
import { Route as AccessRouteImport } from './routes/access'
import { Route as IndexRouteImport } from './routes/index'

const StaffRequestsRoute = StaffRequestsRouteImport.update({
  id: '/staff-requests',
  path: '/staff-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompounderRoute = CompounderRouteImport.update({
  id: '/compounder',
  path: '/compounder',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/compounder': typeof CompounderRoute
  '/dashboard': typeof DashboardRoute
  '/staff-requests': typeof StaffRequestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/compounder': typeof CompounderRoute
  '/dashboard': typeof DashboardRoute
  '/staff-requests': typeof StaffRequestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/compounder': typeof CompounderRoute
  '/dashboard': typeof DashboardRoute
  '/staff-requests': typeof StaffRequestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/access' | '/compounder' | '/dashboard' | '/staff-requests'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/access' | '/compounder' | '/dashboard' | '/staff-requests'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/compounder'
    | '/dashboard'
    | '/staff-requests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  CompounderRoute: typeof CompounderRoute
  DashboardRoute: typeof DashboardRoute
  StaffRequestsRoute: typeof StaffRequestsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff-requests': {
      id: '/staff-requests'
      path: '/staff-requests'
      fullPath: '/staff-requests'
      preLoaderRoute: typeof StaffRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compounder': {
      id: '/compounder'
      path: '/compounder'
      fullPath: '/compounder'
      preLoaderRoute: typeof CompounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  CompounderRoute: CompounderRoute,
  DashboardRoute: DashboardRoute,
  StaffRequestsRoute: StaffRequestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
